services:
  # -------------------
  # BASES DE DATOS
  # -------------------

  users-db:
    image: postgres
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - users_data:/var/lib/postgresql/data
    networks:
      - ecommerce_net

  products-db:
    image: postgres
    environment:
      POSTGRES_DB: products_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - products_data:/var/lib/postgresql/data
    networks:
      - ecommerce_net

  orders-db:
    image: postgres
    environment:
      POSTGRES_DB: orders_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - orders_data:/var/lib/postgresql/data
    networks:
      - ecommerce_net

  # -------------------
  # MICROSERVICIOS DJANGO
  # -------------------

  users-service:
    build: ./backend/users
    volumes:
      - ./backend/users/apps:/usr/src/app/apps
      - ./backend/users/users_project:/usr/src/app/users_project
      - ./backend/users/manage.py:/usr/src/app/manage.py
      - ./secrets/users:/run/secrets:ro
      - ./media/users:/usr/src/app/media
      - static_users:/usr/src/app/staticfiles
      
    ports:
      - "7000:8000"
    env_file:
      - ./backend/users/.env
    depends_on:
      - users-db
    networks:
      - ecommerce_net

  products-service:
    build: ./backend/products
    volumes:
      - ./backend/products/apps:/usr/src/app/apps
      - ./backend/products/products_project:/usr/src/app/products_project
      - ./backend/products/manage.py:/usr/src/app/manage.py
      - ./secrets/products:/run/secrets:ro
      - ./media/products:/usr/src/app/media
      - static_products:/usr/src/app/staticfiles
    ports:
      - "7100:8000"
    env_file:
      - ./backend/products/.env
    depends_on:
      - products-db
    networks:
      - ecommerce_net

  orders-service:
    build: ./backend/orders
    volumes:
      - ./backend/orders/apps:/usr/src/app/apps
      - ./backend/orders/orders_project:/usr/src/app/orders_project
      - ./backend/orders/manage.py:/usr/src/app/manage.py
      - ./secrets/orders:/run/secrets:ro
      - ./media/orders:/usr/src/app/media
      - static_orders:/usr/src/app/staticfiles
    ports:
      - "7200:8000"
    env_file:
      - ./backend/orders/.env
    depends_on:
      - orders-db
    networks:
      - ecommerce_net

# -------------------
# REDIS
# -------------------
  redis-service:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - ecommerce_net

# -------------------
# CELERY WORKERS
# -------------------
  users-celery:
    build: ./backend/users
    command: celery -A users_project worker -l INFO
    volumes:
      - ./backend/users/apps:/usr/src/app/apps
      - ./backend/users/users_project:/usr/src/app/users_project
      - ./secrets/users:/run/secrets:ro
      - ./media/users:/usr/src/app/media
    env_file:
      - ./backend/users/.env
    depends_on:
      - users-service
      - redis-service
    networks:
      - ecommerce_net

  orders-celery:
    build: ./backend/orders
    command: celery -A orders_project worker -l INFO
    volumes:
      - ./backend/orders/apps:/usr/src/app/apps
      - ./backend/orders/orders_project:/usr/src/app/orders_project
      - ./secrets/users:/run/secrets:ro
      - ./media/orders:/usr/src/app/media
    env_file:
      - ./backend/orders/.env
    depends_on:
      - orders-service
      - redis-service
    networks:
      - ecommerce_net

# -------------------
# VOLUMENES Y REDES
# -------------------
volumes:
  users_data:
  products_data:
  orders_data:
  static_users:
  static_products:
  static_orders:

networks:
  ecommerce_net:
    driver: bridge
