# ---------------------------------------------------------------
# Imagen python ligera
# ---------------------------------------------------------------
FROM python:3.12-slim

# ---------------------------------------------------------------
# Seguridad: crear usuario sin privilegios
# ---------------------------------------------------------------
ARG USER_ID=1000
ARG GROUP_ID=1000

RUN groupadd -g $GROUP_ID appuser && \
    useradd -u $USER_ID -g appuser -s /bin/sh -m appuser

# ---------------------------------------------------------------
# Dependencias del sistema necesarias para compilación de paquetes
# ---------------------------------------------------------------
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential libpq-dev \
    # MODIFICACIÓN NECESARIA: Se añade python3-dev para compilar cryptography y otras librerías
    python3-dev \
    && \
    rm -rf /var/lib/apt/lists/*

# ---------------------------------------------------------------
# Variables de entorno
# ---------------------------------------------------------------
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PATH="/home/appuser/.local/bin:$PATH"

# ---------------------------------------------------------------
# Directorio de trabajo dentro del contenedor
# ---------------------------------------------------------------
WORKDIR /usr/src/app

# ---------------------------------------------------------------
# Instalación de dependencias
# ---------------------------------------------------------------
COPY --chown=appuser:appuser requirements.txt .

RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# ---------------------------------------------------------------
# Copiar el código fuente de la aplicación
# ---------------------------------------------------------------
COPY --chown=appuser:appuser . .

# ---------------------------------------------------------------
# Copiar y configurar script entrypoint
# ---------------------------------------------------------------
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# ---------------------------------------------------------------
# Configurar entrypoint
# ---------------------------------------------------------------
ENTRYPOINT ["/entrypoint.sh"]
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]