# Generated by Django 5.2.8 on 2025-11-20 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('zone', models.CharField(choices=[('NORTH', 'Zona Norte'), ('CENTER', 'Zona Centro'), ('SOUTH', 'Zona Sur')], db_index=True, max_length=10)),
            ],
            options={
                'verbose_name': 'Región',
                'verbose_name_plural': 'Regiones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comunas', to='locations.region')),
            ],
            options={
                'verbose_name': 'Comuna',
                'verbose_name_plural': 'Comunas',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['region', 'name'], name='locations_c_region__b92e2d_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'region'), name='unique_comuna_region')],
            },
        ),
    ]
