# Generated by Django 6.0.2 on 2026-02-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmeasureunit',
            name='name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Unidad de medida'),
        ),
        migrations.AlterField(
            model_name='measureunit',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Unidad de medida'),
        ),
    ]
