# Generated by Django 5.2.8 on 2025-11-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_historicaluser_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=9, verbose_name='Número celular'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=9, unique=True, verbose_name='Número celular'),
        ),
    ]
