# Generated by Django 5.2.8 on 2025-11-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_historicaluser_is_verified_user_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=9, null=True, verbose_name='Número celular'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True, verbose_name='Número celular'),
        ),
    ]
