# Generated by Django 6.0.2 on 2026-02-07 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('users', '0004_alter_historicaluser_phone_alter_user_phone'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_main', True)), fields=('user',), name='unique_active_main_address_constraint'),
        ),
    ]
