# Generated by Django 6.0.1 on 2026-02-02 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('created_by', models.IntegerField(blank=True, null=True, verbose_name='Creado por')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('modified_by', models.IntegerField(blank=True, null=True, verbose_name='Modificado por')),
                ('deleted_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('deleted_by', models.IntegerField(blank=True, null=True, verbose_name='ID de usuario')),
                ('user_id', models.IntegerField(verbose_name='Orden del usuario')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PAID', 'Pagado'), ('CANCELLED', 'CANCELADO')], default='PENDING', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=8, verbose_name='Total orden')),
            ],
            options={
                'verbose_name': 'Modelo base',
                'verbose_name_plural': 'Modelos base',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.IntegerField(verbose_name='ID del producto')),
                ('quantity', models.IntegerField(verbose_name='Cantidad del producto')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=8, verbose_name='Precio unitario')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.order')),
            ],
        ),
    ]
