# Generated by Django 6.0.2 on 2026-02-08 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options_alter_orderdetail_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorderdetail',
            name='product_title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre del producto'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='product_title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre del producto'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('PAID', 'Pagado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('PAID', 'Pagado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20),
        ),
    ]
