# Generated by Django 6.0.3 on 2026-03-17 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_historicalorderdetail_product_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorderdetail',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL de imágen del producto'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL de imágen del producto'),
        ),
    ]
