# Generated by Django 6.0.4 on 2026-04-09 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_historicalorderdetail_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='user_address',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dirección de envío'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_address',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dirección de envío'),
        ),
        migrations.AlterField(
            model_name='historicalorder',
            name='deleted_by',
            field=models.IntegerField(blank=True, null=True, verbose_name='Eliminado por'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deleted_by',
            field=models.IntegerField(blank=True, null=True, verbose_name='Eliminado por'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user_id'], name='orders_orde_user_id_a87c6f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'),
        ),
    ]
