upstream users_backend {
    server users-service:8000;
    }
upstream products_backend {
    server products-service:8000;
    }
upstream orders_backend {
    server orders-service:8000;
    }

server {
    listen 80;
    server_name api.guitarzone.cl;

    # Configuracion mapeo de APIs
    location /users/ {
        rewrite ^/users/(.*)$ /users-api/$1 break;
        proxy_pass http://users_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }


    location /products/ {
        rewrite ^/products/(.*)$ /products-api/$1 break;
        proxy_pass http://products_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /orders/ {
        rewrite ^/orders/(.*)$ /orders-api/$1 break;
        proxy_pass http://orders_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }


    # Configuracion de static
    location /static/users/ {
        alias /usr/src/app/static_users;
    }

    location /static/products/ {
        alias /usr/src/app/static_products;
    }

    location /static/orders/ {
        alias /usr/src/app/static_orders;
    }


    # Configuracion de Media

    location /media/users/ {
        alias /usr/src/app/media_users;
    }

    location /media/products/ {
        alias /usr/src/app/media_products;
    }

    location /media/orders/ {
        alias /usr/src/app/media_orders;
    }

}